### PR TITLE
Fusion Auth Client need support ssl

### PR DESCRIPTION
**Pull request by zhengchengyang**
I suggest fusionauth java client need support ssl for prodution use，it's my way，need you to rewite it

### CODE REVIEW

**Comment by mooreds** [comment]
Thanks for the PR, @zhengchengyang !

Is this to support custom or self-signed SSL certs? Or for some other reason?

**Comment by robotdan** [comment]
Usually we add custom certs of self-signed that aren't otherwise trusted to the Java trust store. But this could work as well. If we want to accept this, the changes to FusionAuth client would have to be rebuilt into the template. 
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/java.client.ftl

**Comment by mooreds** [comment]
I would suggest we stick with the java trust store option and perhaps document it, as that is more typical. 

@zhengchengyang would that work for your use case?

**Comment by zhengchengyang** [comment]
> Thanks for the PR, @zhengchengyang !
> 
> Is this to support custom or self-signed SSL certs? Or for some other reason?

The reason is because the fusionauth service used by our company is deployed through ssl. I use this client to access, and when the interface is called, it will prompt that the certificate verification fails. Therefore, it is recommended that the client support ssl to access the fusionauth service.

**Comment by mooreds** [comment]
Hmmm. You should be able to request https://localhost:9013 which serves up SSL requests without modifying the java client. 

Another option that many folks use is a proxy: https://fusionauth.io/docs/v1/tech/admin-guide/proxy-setup

**Comment by zhengchengyang** [comment]
> Hmmm. You should be able to request https://localhost:9013 which serves up SSL requests without modifying the java client.
> 
> Another option that many folks use is a proxy: https://fusionauth.io/docs/v1/tech/admin-guide/proxy-setup

oh i see, thanks for your guide. it's a better way to solve this problem

**Pull request closed without merging**
